# Generated by Django 4.2.6 on 2023-10-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('inn', models.IntegerField(unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_unit', models.CharField(max_length=1000)),
                ('sout_card_number', models.CharField(max_length=50)),
                ('place_id', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=500)),
                ('workers_quantity', models.IntegerField()),
                ('profession', models.IntegerField()),
                ('date_sout', models.DateField()),
                ('status', models.CharField(choices=[('CR', 'Создано'), ('CH', 'Проверено'), ('WA', 'Предупреждение'), ('ER', 'Ошибка')], default='CR', max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification_app.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='FileXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_xml', models.FileField(upload_to='xml_files')),
                ('date', models.DateField()),
                ('sout_id', models.IntegerField(unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification_app.organisation')),
            ],
        ),
    ]
