# Generated by Django 4.2.6 on 2024-04-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSOUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_xml', models.FileField(upload_to='xml_files')),
                ('date', models.DateField()),
                ('sout_id', models.IntegerField(blank=True, null=True)),
                ('work_places_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('inn', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_unit', models.CharField(max_length=1000)),
                ('sout_card_number', models.CharField(max_length=50)),
                ('place_id', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=500)),
                ('workers_quantity', models.IntegerField()),
                ('profession', models.IntegerField(blank=True, null=True)),
                ('date_sout', models.DateField()),
                ('status', models.CharField(choices=[('CH', 'Проверено'), ('WA', 'Предупреждение'), ('NU', 'Не используется')], default='CH', max_length=2)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification_app.filesout')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification_app.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='filesout',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification_app.organisation'),
        ),
        migrations.AddConstraint(
            model_name='filesout',
            constraint=models.UniqueConstraint(fields=('date', 'organization'), name='unique_date_organization'),
        ),
    ]
