# Generated by Django 4.2.6 on 2024-04-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesout',
            options={'ordering': ('-date', 'organization'), 'verbose_name': 'Файл СОУТ', 'verbose_name_plural': 'Файлы СОУТ'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',), 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ('date_sout',), 'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
    ]
