# Generated by Django 4.2.6 on 2024-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_app', '0002_alter_filesout_options_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workplace',
            index=models.Index(fields=['file'], name='verificatio_file_id_3fab72_idx'),
        ),
        migrations.AddIndex(
            model_name='workplace',
            index=models.Index(fields=['organization', 'status'], name='organization__status'),
        ),
    ]
