# Generated by Django 4.2.6 on 2024-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_app', '0003_workplace_verificatio_file_id_3fab72_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['inn'], name='inn_unique'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['name'], name='name_organization'),
        ),
    ]
